#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Regex: SE-123: anything
pattern="^SE-[0-9]+: .+"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo ""
  echo "❌ Invalid commit message format!"
  echo "✔ Expected format: SE-X: your message"
  echo ""
  exit 1
fi

exit 0
